# Generated by Django 4.2 on 2023-04-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=64)),
                ('speciality', models.CharField(max_length=64)),
                ('salary', models.FloatField()),
                ('education', models.CharField(max_length=64)),
                ('experience', models.TextField()),
                ('portfolio', models.URLField()),
                ('title', models.CharField(max_length=64)),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
